# typed: false
# frozen_string_literal: true

# IronClaw — security-hardened, self-hosted AI assistant platform.
#
# This formula is GENERATED by scripts/update-homebrew-formula.sh from a published
# release's SHA256SUMS — do not hand-edit the version/url/sha256 lines. To track a
# newer release, re-run that script and commit the result.
#
# Install:  brew tap IronSecCo/ironclaw https://github.com/IronSecCo/ironclaw
#           brew install ironsecco/ironclaw/ironclaw
#
# NOTE: homebrew-core ships an UNRELATED formula also named "ironclaw", and core
# wins the bare name. Always install the fully-qualified tap formula above; a bare
# "brew install ironclaw" would fetch the core package, not this one.
class Ironclaw < Formula
  desc "Security-hardened, self-hosted AI assistant platform (secured Go port)"
  homepage "https://github.com/IronSecCo/ironclaw"
  version "0.1.470"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.470/ironclaw_0.1.470_darwin_arm64.tar.gz"
      sha256 "8e5b50942af5f2ef96378c6c75cc391567db0ce26003317b6ea0f066ce89f06d"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.470/ironclaw_0.1.470_darwin_amd64.tar.gz"
      sha256 "75963526882cdfa5b157fbadde94c1c22fad091ba5669afe7a72dd24e67ac0ad"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.470/ironclaw_0.1.470_linux_arm64.tar.gz"
      sha256 "a6bbb095548020abd35cef3c247ec4149c99d5b5634aefffdfbf1842dcee4a47"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.470/ironclaw_0.1.470_linux_amd64.tar.gz"
      sha256 "6fa6d049ba6f2bad1d77489989be969bc2fcddd26ce4d0ea579416337fa68c4f"
    end
  end

  def install
    bin.install "ironctl"
    bin.install "ironclaw-controlplane"
    bin.install "ironclaw-sandbox"
  end

  def caveats
    <<~EOS
      ironctl, ironclaw-controlplane, and ironclaw-sandbox are now on your PATH.

      Get started:
        ironctl version
        ironctl doctor      # preflight: model creds, toolchain, sockets

      For production the control plane usually runs as a container:
        ghcr.io/ironsecco/ironclaw-controlplane:v0.1.470
      See https://ironsecco.github.io/ironclaw/quickstart/ for the full first-run flow.
    EOS
  end

  test do
    assert_match "ironctl v#{version}", shell_output("#{bin}/ironctl version")
  end
end
