# typed: false
# frozen_string_literal: true

# IronClaw — security-hardened, self-hosted AI assistant platform.
#
# This formula is GENERATED by scripts/update-homebrew-formula.sh from a published
# release's SHA256SUMS — do not hand-edit the version/url/sha256 lines. To track a
# newer release, re-run that script and commit the result.
#
# Install:  brew tap IronSecCo/ironclaw https://github.com/IronSecCo/ironclaw
#           brew install ironsecco/ironclaw/ironclaw
#
# NOTE: homebrew-core ships an UNRELATED formula also named "ironclaw", and core
# wins the bare name. Always install the fully-qualified tap formula above; a bare
# "brew install ironclaw" would fetch the core package, not this one.
class Ironclaw < Formula
  desc "Security-hardened, self-hosted AI assistant platform (secured Go port)"
  homepage "https://github.com/IronSecCo/ironclaw"
  version "0.1.450"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.450/ironclaw_0.1.450_darwin_arm64.tar.gz"
      sha256 "38d1eb7be46718599ead7a7f5de024c23947f95b18e4719176c4e14bef4f4763"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.450/ironclaw_0.1.450_darwin_amd64.tar.gz"
      sha256 "88bca4bfbcf4f129d5e0b43048274ac5d6bf1d04e6478c6af13c4a1f41005e9b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.450/ironclaw_0.1.450_linux_arm64.tar.gz"
      sha256 "af6d45c775637e73d26ec1110c80de3bbe9b563e6939960059d314df7fb603e8"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.450/ironclaw_0.1.450_linux_amd64.tar.gz"
      sha256 "287744ee5f444811d9db2341daf805deddb16dd13eed7313a95375df70de5640"
    end
  end

  def install
    bin.install "ironctl"
    bin.install "ironclaw-controlplane"
    bin.install "ironclaw-sandbox"
  end

  def caveats
    <<~EOS
      ironctl, ironclaw-controlplane, and ironclaw-sandbox are now on your PATH.

      Get started:
        ironctl version
        ironctl doctor      # preflight: model creds, toolchain, sockets

      For production the control plane usually runs as a container:
        ghcr.io/ironsecco/ironclaw-controlplane:v0.1.450
      See https://ironsecco.github.io/ironclaw/quickstart/ for the full first-run flow.
    EOS
  end

  test do
    assert_match "ironctl v#{version}", shell_output("#{bin}/ironctl version")
  end
end
